
graphql:
  packages: "src.main.kotlin.de.novatec.productservice"

spring:
  data:
    mongodb:
      port: 27017
      database: GraphqlDemoShopDb
      host: localhost

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG